CC = gcc
CFLAGS = -Wall -Werror -pthread
SRCDIR = server client
OBJDIR = obj
BINDIR = target

SRC = $(foreach dir, $(SRCDIR), $(wildcard $(dir)/*.c))
OBJ = $(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(SRC))
TARGET = $(BINDIR)/server

.PHONY: all clean

all: $(TARGETSERVER) $(TARGETCLIENT)

$(TARGETSERVER): $(OBJSERVER)
	$(CC) $(CFLAGS) $^ -o $@ 

$(TARGETCLIENT): $(OBJCLIENT)
	$(CC) $(CFLAGS) $^ -o $@ 

$(OBJDIR)/%.o: server/%.c
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR)/%.o: client/%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJDIR)/*.o $(OBJDIR)/*.o $(TARGETSERVER) $(TARGETCLIENT)